options_schema = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "maxPercentageDifferences": {
            "type": "object",
            "properties": {"buy": {"type": "number"}, "sell": {"type": "number"}},
            "required": ["buy", "sell"],
            "additionalProperties": False,
        },
        "intervals": {
            "type": "object",
            "properties": {"snapshot": {"type": "number"}, "price": {"type": "number"}, "pricelist": {"type": "number"}, "key": {"type": "number"}},
            "required": ["snapshot", "price", "pricelist", "key"],
            "additionalProperties": False,
        },
        "pricingOptions": {
            "type": "object",
            "properties": {
                "onlyBots": {"type": "boolean"},
                "allowCutting": {"type": "boolean"},
                "allowSnipping": {"type": "boolean"},
                "allowMatching": {"type": "boolean"},
                "allowRounding": {"type": "boolean"},
                "allowBacking": {"type": "boolean"},
                "buyLimit": {"type": "number"},
                "sellLimit": {"type": "number"},
                "buyLimitStrict": {"type": "boolean"},
                "sellLimitStrict": {"type": "boolean"},
                "buyHumanFallback": {"type": "boolean"},
                "sellHumanFallback": {"type": "boolean"},
                "partialBuyFallback": {"type": "boolean"},
                "partialSellFallback": {"type": "boolean"},
            },
            "required": [
                "onlyBots",
                "allowCutting",
                "allowSnipping",
                "allowMatching",
                "allowRounding",
                "allowBacking",
                "buyLimit",
                "sellLimit",
                "buyLimitStrict",
                "sellLimitStrict",
                "buyHumanFallback",
                "sellHumanFallback",
                "partialBuyFallback",
                "partialSellFallback",
            ],
            "additionalProperties": False,
        },
        "enforceKeyFallback": {"type": "boolean"},
        "excludedSteamIDs": {"type": "array", "items": {"type": "string"}},
        "trustedSteamIDs": {"type": "array", "items": {"type": "string"}},
        "excludedListingDescriptions": {"type": "array", "items": {"type": "string"}},
        "blockedAttributes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {"name": {"type": "string"}, "defindex": {"type": "number"}},
                "required": ["defindex"],
                "additionalProperties": False,
            },
        },
        "paints": {"type": "array", "items": {"type": "string"}},
    },
    "required": [
        "maxPercentageDifferences",
        "intervals",
        "pricingOptions",
        "enforceKeyFallback",
        "excludedSteamIDs",
        "trustedSteamIDs",
        "excludedListingDescriptions",
        "blockedAttributes",
        "paints",
    ],
    "additionalProperties": False,
}
